---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: envoy-502-upe
  name: envoy-502-upe
  namespace: default
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: http
  selector:
    app: envoy-502-upe
  type: ClusterIP
